version: "2"

services:
   # Base de données
   wordpress-db:
     container_name: wordpress-db
     image: mysql:5.7
     volumes:
       - /apps/wordpress/db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: $DB_ROOT
       MYSQL_DATABASE: wordpress
       MYSQL_USER: $DB_USER
       MYSQL_PASSWORD: $DB_PASSWORD

     #Facultatif
     networks:
       - proxy
     logging:
       driver: loki
       options:
         loki-url: "$URL_LOKI"
         loki-external-labels: service={{.Name}}

   wordpress:
     container_name: wordpress
     depends_on:
       - wordpress-db
     image: wordpress:latest
     restart: always
     volumes:
       - /apps/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - /apps/wordpress/html:/var/www/html
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_USER: $DB_USER
       WORDPRESS_DB_PASSWORD: $DB_PASSWORD
       WORDPRESS_DB_NAME: wordpress
    #Facultatif avec Traefik
#    ports:
#     - 8080:80

     # Facultatif
     networks:
       - proxy
     logging:
       driver: loki
       options:
         loki-url: "$URL_LOKI"
         loki-external-labels: service={{.Name}}
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.wordpress.entrypoints=http"
       - "traefik.http.routers.wordpress.rule=Host(`$URL_WEBSITE`)"
       - "traefik.http.middlewares.wordpress-https-redirect.redirectscheme.scheme=https"
       - "traefik.http.routers.wordpress.middlewares=wordpress-https-redirect"
       - "traefik.http.routers.wordpress-secure.entrypoints=https"
       - "traefik.http.routers.wordpress-secure.rule=Host(`$URL_WEBSITE`)"
       - "traefik.http.routers.wordpress-secure.tls=true"
       - "traefik.http.routers.wordpress-secure.tls.certresolver=http"
       - "traefik.docker.network=proxy"

networks:
  proxy:
    external:
      name: proxy
