version: "3.7"
 
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - testdb #Which we deployed using MariaDB
    volumes:
      - /mnt/wordpressdata:/var/www/html/wp-content
    secrets:
      - wp_db_password
    environment:
      - WORDPRESS_DB_HOST=testdb:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_NAME=wordpressdb
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_db_password
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.wordpress.rule=Host(`youtech-consulting.com`)"
        - "traefik.http.routers.wordpress.tls=true"
        - "traefik.http.routers.wordpress.tls.certresolver=default"
        - "traefik.http.routers.wordpress.entrypoints=websecure"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"
secrets:
  wp_db_password:
    external: true 
volumes:
  wordpressdata:
    driver: "local"
networks:
  proxy:
    external: true
